
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 07:57:09 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 29;
  public static final int INCREMENT = 33;
  public static final int CONST = 6;
  public static final int EQUALS = 32;
  public static final int NAMESPACE = 18;
  public static final int NUMCONST = 50;
  public static final int LPAREN = 39;
  public static final int CONTINUE = 14;
  public static final int FOR = 16;
  public static final int MINUS = 20;
  public static final int DECREMENT = 34;
  public static final int RPAREN = 40;
  public static final int STATIC = 17;
  public static final int SEMICOLON = 35;
  public static final int AND = 30;
  public static final int LT = 28;
  public static final int OR = 31;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int IF = 7;
  public static final int THIS = 15;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 21;
  public static final int PERCENT = 23;
  public static final int IDENT = 51;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int GTE = 27;
  public static final int ARROW = 45;
  public static final int FOREACH = 48;
  public static final int COLON = 36;
  public static final int LBRACE = 43;
  public static final int ELSE = 5;
  public static final int LSQUARE = 41;
  public static final int READ = 10;
  public static final int CHARCONST = 53;
  public static final int WHILE = 47;
  public static final int RSQUARE = 42;
  public static final int NOT_EQUALS = 25;
  public static final int RBRACE = 44;
  public static final int BOOLCONST = 52;
  public static final int EXTENDS = 13;
  public static final int EQUALS_EQUALS = 24;
  public static final int MAX = 46;
  public static final int GT = 26;
  public static final int DO = 49;
  public static final int PRINT = 9;
}

